Title: SMART TRAFFIC MANAGEMENT SYSTEM.
Description: A Smart Traffic Management System collects real-time data from cameras, sensors, and GPS devices to monitor traffic conditions. 
theme:jekyll_theam_cayman
